{% set ML_FINC_PRD = var('ML_FINC_PRD') %}
{% set POP_INFO_ID = var('POP_INFO_ID') %}
{% set BATCH_ID = var('BATCH_ID') %}
{% set SRC_SYS_CD_LIC_CMTN = var('SRC_SYS_CD_LIC_CMTN') %}
{% set DBOwnerWRK = var('DBOwnerWRK') %}
WITH 
    partition1 AS (
        -- Partition 1: Example using WORK_ACTU_ADJT (actual partition query would be much more detailed)
        SELECT
            NEXTVAL('znawwrkdb.dbaall.SEQ_WRK_IFRS_LIC_CALC_PK') AS WRK_IFRS_LIC_CALC_PK,
            UPPER(MD5(RTRIM(IBNR_FAM_CD) || RTRIM(FINC_ACC_EXPO_CC_YY) || RTRIM(LOCL_CRCY_CD) || RTRIM(LOS_PORT_XFER_IND) || RTRIM(LOS_PORT_XFER_CD))) AS ACTU_ADJT_BNRY_ID,
            UPPER(MD5(RTRIM(IBNR_FAM_CD) || RTRIM(FINC_ACC_EXPO_CC_YY) || RTRIM(LOCL_CRCY_CD) || RTRIM(LOS_PORT_XFER_IND) || RTRIM(LOS_PORT_XFER_CD))) AS IBNR_AY_LC_BNRY_ID,
            NULL AS CL_PPAY_LKD_YC_LPT_BNRY_ID,
            NULL AS CL_PPAY_CUR_YC_LPT_BNRY_ID,
            NULL AS CL_PPAY_CUR_YCQ_LPT_BNRY_ID,
            NULL AS OPN_PPAY_LKD_YC_BNRY_ID,
            NULL AS OPN_PPAY_CUR_YC_LPT_BNRY_ID,
            NULL AS IBNR_CORPLOB_BNRY_ID,
            ACQN_ALT_BUSN_KEY, ACTU_PRFT_LN_ALT_BUSN_KEY, ASSM_REINS_AGMT_ALT_BUSN_KEY, BNDL_ALT_BUSN_KEY, CEDE_REINS_AGMT_ALT_BUSN_KEY, CMTN_AGMT_ALT_BUSN_KEY, COVG_LOB_ALT_BUSN_KEY, DIR_ASSM_CEDE_ALT_BUSN_KEY,
            EXC_ALT_BUSN_KEY, FINC_COVG_LOB_ALT_BUSN_KEY, FINC_INSR_ALT_BUSN_KEY, FINC_INT_ORG_ALT_BUSN_KEY, FINC_LOB_ALT_BUSN_KEY, FINC_ST_ALT_BUSN_KEY, IBNR_FAM_ALT_BUSN_KEY, INS_TYP_ALT_BUSN_KEY, INSR_ALT_BUSN_KEY, INT_ORG_ALT_BUSN_KEY, RETRO_RATG_ALT_BUSN_KEY, ST_ALT_BUSN_KEY, TYP_INS_ALT_BUSN_KEY, CROP_REINS_YY,
            'C' AS CUR_PRIR_IND,
            IBNR_FAM_CD, FINC_ACC_EXPO_CC_YY,
            TO_DATE('{{ ML_FINC_PRD }}01') AS FINC_CL_PERD_DT,
            ITER_ID, POL_EFF_CC_YY, RETRO_CEDE_IND,
            CASE WHEN IBNR_FAM_CD = '049000' THEN '{{ SRC_SYS_CD_LIC_CMTN }}' ELSE SRC_SYS_CD END AS SRC_SYS_CD,
            CALC_SRC_SYS_CD, ULAE_GP_CD, ULT_REINS_AGMT_NBR, ACTU_UNT_OF_ACCT_DERVN_ALT_BUSN_KEY, ORGL_ACTU_UNT_OF_ACCT_DERVN_ALT_BUSN_KEY,
            DRVD_FINC_LOS_CATG_ALT_BUSN_KEY, 
            OPN_PYMT_PTRN_CD, CL_PYMT_PTRN_CD, OPN_CUR_YLD_CURVE_CRCY_CD, OPN_LKD_YLD_CURVE_CRCY_CD, CL_CUR_YLD_CURVE_CRCY_CD, CL_LKD_YLD_CURVE_CRCY_CD, LOCL_CRCY_CD, NULL AS FUT_QTR,
            CORP_LOB_CD, DATA_UNT,
            CASE WHEN CEDE_REINS_AGMT_ALT_BUSN_KEY = -1 AND CMTN_AGMT_ALT_BUSN_KEY <> -1 THEN 'N' ELSE CASE WHEN CMTN_AGMT_ALT_BUSN_KEY = -1 THEN 'N' ELSE 'Y' END END AS SRC_REC_CMTN_IND,
            SRC_REC_UUBVI_ELIM_IND, 'WAA' AS SRC_TAB_NM, EXEC_SEQ, 
            IFRS_MNTRY_TYP_ID,
            SUM(LOCL_AMT) AS LOCL_AMT, LOCL_CRCY_ALT_BUSN_KEY,
            SUM(REVAL_CUR_LOCL_AMT) AS REVAL_CUR_LOCL_AMT, SUM(REVAL_LOCL_CHG_AMT) AS REVAL_LOCL_CHG_AMT,
            SUM(TRAN_AMT) AS TRAN_AMT, TRAN_CRCY_ALT_BUSN_KEY, SUM(CONTR_AMT) AS CONTR_AMT, CONTR_CRCY_ALT_BUSN_KEY,
            CURRENT_TIMESTAMP() AS EFF_FM_TISTMP, TO_DATE('2999-12-31') AS EFF_TO_TISTMP, 
            {{ POP_INFO_ID }} AS POP_INFO_ID, {{ POP_INFO_ID }} AS UPDT_POP_INFO_ID, {{ BATCH_ID }} AS BAT_ID, 
            NULL AS IBNR_AY_LKD_YC_LPT_BNRY_ID, CLR_HOUS_POL_CATG_ALT_BUSN_KEY, INTL_PGM_PRODG_CTRY_ALT_BUSN_KEY, INTL_PGM_RECV_CTRY_ALT_BUSN_KEY, SRC_LOB_ALT_BUSN_KEY, 
            SUM(REVAL_CUR_CONTR_AMT) AS REVAL_CUR_CONTR_AMT, SUM(REVAL_CONTR_CHG_AMT) AS REVAL_CONTR_CHG_AMT,
            TRIM(CASE WHEN LOS_PORT_XFER_IND = 'UNK' THEN 'N' ELSE LOS_PORT_XFER_IND END) AS LOS_PORT_XFER_IND, LOS_PORT_XFER_CD, NULL AS OPN_PPAY_LKD_YC_LPT_BNRY_ID, FINC_SERV_ROL_FOR_REINS_ALT_BUSN_KEY
        FROM {{ ref('stg_work_actu_adjt') }}
        GROUP BY ACQN_ALT_BUSN_KEY, ACTU_PRFT_LN_ALT_BUSN_KEY, ASSM_REINS_AGMT_ALT_BUSN_KEY, BNDL_ALT_BUSN_KEY, CEDE_REINS_AGMT_ALT_BUSN_KEY, CMTN_AGMT_ALT_BUSN_KEY, COVG_LOB_ALT_BUSN_KEY, DIR_ASSM_CEDE_ALT_BUSN_KEY,
            EXC_ALT_BUSN_KEY, FINC_COVG_LOB_ALT_BUSN_KEY, FINC_INSR_ALT_BUSN_KEY, FINC_INT_ORG_ALT_BUSN_KEY, FINC_LOB_ALT_BUSN_KEY, FINC_ST_ALT_BUSN_KEY, IBNR_FAM_ALT_BUSN_KEY, INS_TYP_ALT_BUSN_KEY, INSR_ALT_BUSN_KEY, INT_ORG_ALT_BUSN_KEY, RETRO_RATG_ALT_BUSN_KEY, ST_ALT_BUSN_KEY, TYP_INS_ALT_BUSN_KEY, CROP_REINS_YY,
            IBNR_FAM_CD, FINC_ACC_EXPO_CC_YY, ITER_ID, POL_EFF_CC_YY, RETRO_CEDE_IND, SRC_SYS_CD, CALC_SRC_SYS_CD, ULAE_GP_CD, ULT_REINS_AGMT_NBR, ACTU_UNT_OF_ACCT_DERVN_ALT_BUSN_KEY, ORGL_ACTU_UNT_OF_ACCT_DERVN_ALT_BUSN_KEY, DRVD_FINC_LOS_CATG_ALT_BUSN_KEY,
            OPN_PYMT_PTRN_CD, CL_PYMT_PTRN_CD, OPN_CUR_YLD_CURVE_CRCY_CD, OPN_LKD_YLD_CURVE_CRCY_CD, CL_CUR_YLD_CURVE_CRCY_CD, CL_LKD_YLD_CURVE_CRCY_CD, LOCL_CRCY_CD, CORP_LOB_CD, DATA_UNT, SRC_REC_UUBVI_ELIM_IND, EXEC_SEQ, IFRS_MNTRY_TYP_ID, LOCL_CRCY_ALT_BUSN_KEY, TRAN_CRCY_ALT_BUSN_KEY, CONTR_CRCY_ALT_BUSN_KEY, CLR_HOUS_POL_CATG_ALT_BUSN_KEY, INTL_PGM_PRODG_CTRY_ALT_BUSN_KEY, INTL_PGM_RECV_CTRY_ALT_BUSN_KEY, SRC_LOB_ALT_BUSN_KEY, LOS_PORT_XFER_IND, LOS_PORT_XFER_CD, FINC_SERV_ROL_FOR_REINS_ALT_BUSN_KEY
    ),
    -- Partition 2: Add remaining five CTEs per full mapping; below are examples/templates.
    partition2 AS (
        SELECT * FROM {{ ref('stg_fact_actu_adjt_accum_mm') }} -- stub; replace with partition2 business logic
    ),
    partition3 AS (
        SELECT * FROM {{ ref('stg_wrk_actu_adjt_rstmt_opn_pymt_ptrn') }} -- stub; replace with partition3 business logic
    ),
    partition4 AS (
        SELECT * FROM {{ ref('stg_wrk_ifrs_qtr_incr_paid') }} -- stub; replace with partition4 business logic
    ),
    partition5 AS (
        SELECT * FROM {{ ref('stg_wrk_actu_adjt_port_xfer') }} -- stub; replace with partition5 business logic
    ),
    partition6 AS (
        SELECT * FROM {{ ref('stg_other_sources') }} -- stub; adjust as per sixth logical partition
    )
SELECT * FROM partition1
UNION ALL
SELECT * FROM partition2
UNION ALL
SELECT * FROM partition3
UNION ALL
SELECT * FROM partition4
UNION ALL
SELECT * FROM partition5
UNION ALL
SELECT * FROM partition6
