version: 2

models:
  - name: ref_int_customer
    description: "Customer master table"

    columns:

      - name: customer_id
        description: "Primary key of customer"
        tests:
          - not_null
          - unique

      - name: country_code
        description: "Country of the customer"
        tests:
          - not_null
          - relationships:
              to: ref('stg_country')
              field: country_code
              config:
                severity: error
              #where: "is_active = true"

      - name: customer_type
        description: "Customer classification"
        tests:
          - not_null
          - accepted_values:
              values: ['RETAIL','CORPORATE','GOVT']
          - relationships:
              to: ref('stg_customer_type')
              field: customer_type
              #where: "is_active = true"

      - name: amount
        tests:
          - not_null

      - name: business_date
        tests:
          - not_null

      - name: load_ts
        tests:
          - not_null
